### ISSUE TITLE
base ramification git config

### ISSUE THREAD

**Issue by jonariv09** [js-ni/covid-spa#3]
Patrón para la ramificación del repo de git

**Comment by hosmelq** [comment]
Sugiero que usemos gitflow

**Comment by luchonetvv** [comment]
Me gusta la idea Hosmel.

**Comment by clenondavis** [comment]
Si solo manejaremos 2 ambientes `dev` y `prod/master` apoyo la mosión.
No obstante, como administra `gitflow` el ambiente de las pruebas `QA` u otros ambientes?. 
Como lo hacen ustedes?

**Comment by hosmelq** [comment]
En gitflow tienes master, develop, feature, release y hotfix donde master es prod y develop staging los features se manejan a como ya los estas manejando y los releases cada que se haga un release(valga la redundancia) y los hotfix son para corregir errores directamente en prod sin pasar por develop. [Aquí](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) puedes leer más sobre como funciona.

**Comment by carloslenondavis** [comment]
Entiendo. He trabajado con gitflow y domino la estructura y el cli que propone. Pero deje de usarlo unos 2 o 3 años atras. Por eso pregunte, a ver si había algo diferente. 

Si para testear publicaremos `develop` y ahí se harán todos los testing, no tengo problemas. Creo que son temas muy complicados de discutir por comentarios.

Creo que para `covid-19` no hay problema que se use gitflow como cli y standard para las ramificaciones

Demosle, lo importante es sacar el `MVP` lo mas rapido posible

**Comment by carloslenondavis** [comment]
Usaremos gitflow

**Comment by luchonetvv** [comment]
Recomiendo utilizar esta manera para escribir un buen commit.

How to Write a Git Commit Message <https://chris.beams.io/posts/git-commit/>
