### ISSUE TITLE
rules for coding

### ISSUE THREAD

**Issue by jonariv09** [js-ni/covid-spa#5]
Estilos, reglas y formato a utilizar en el codigo

**Comment by clenondavis** [comment]
1. Baso en propuestas revisando[ standardjs](https://standardjs.com/rules.html)
2. Revisando [coding style community](https://javascript.info/coding-style)
3. Revisando [facebook coding standars](https://github.com/facebook/jcommon/wiki/Coding-Standards)
4. Revisando [google coding style](https://google.github.io/styleguide/jsguide.html)
5. Revisando [arbnb coding style](https://github.com/airbnb/javascript)

**Comment by carloslenondavis** [comment]
Usaremos `standardjs`
